"""
Django settings for sreadmin project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib import admin

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ADMINLTE_THEME_NAME = 'admin-lte'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7%dlz(gef)_%-e+@06l=35oj)f3)n!83nj!ee#scafw*syz%w%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['200.115.107.79', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'adminlte4',
    'adminlte4_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'painel', # Certifique-se de que seu app 'painel' está aqui!
    'captive_portal',  # App virtual para organizar menus Captive Portal
    # Outros apps...
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Para tradução
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'painel.middleware.AdminTranslationMiddleware',  # Middleware de tradução personalizada (desabilitado temporariamente)
]

ROOT_URLCONF = 'sreadmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'painel', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sreadmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'radiusd',
        'USER': 'postgres',
        'PASSWORD': '123.1234',
        'HOST': 'localhost',  # Ou o endereço do seu servidor PostgreSQL
        'PORT': '5432',       # Porta padrão do PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo' # Ou 'UTC' se você preferir que o Django armazene tudo em UTC e converta para o fuso horário do usuário.

USE_I18N = True # Manter como True para habilitar internacionalização

USE_L10N = True  # Habilita formatação localizada

USE_TZ = True # Manter como True para habilitar suporte a fusos horários

# Diretório para arquivos de tradução
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Idiomas disponíveis
LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
    ('en', 'English'),
]

# Forçar uso da localização brasileira
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3

# Configurações de formatação para Brasil
DATE_FORMAT = 'd/m/Y'
TIME_FORMAT = 'H:i'
DATETIME_FORMAT = 'd/m/Y H:i'
YEAR_MONTH_FORMAT = 'm/Y'
MONTH_DAY_FORMAT = 'd/m'
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'
FIRST_DAY_OF_WEEK = 1  # Segunda-feira

# Configurações de localização
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações do AdminLTE4
ADMINLTE_SETTINGS = {
    'title': 'POPPFIRE ADMIN',
    'title_short': 'POPPFIRE',
    'skin': 'blue',
    'logo': {
        'image': 'img/logo_app.png',
        'text': 'POPPFIRE ADMIN',
        'text_small': 'POPPFIRE',
    },
    'navbar': {
        'class': 'navbar-primary navbar-dark',
        'fixed': True,
    },
    'sidebar': {
        'class': 'sidebar-dark-primary',
        'mini': True,
        'fixed': True,
    },
    'layout': {
        'fixed': True,
        'boxed': False,
    },
}

# Configurações específicas do AdminLTE4
ADMINLTE4_LOGO_IMAGE = 'img/logo_app.png'
ADMINLTE4_LOGO_TEXT = 'POPPFIRE ADMIN'
ADMINLTE4_LOGO_TEXT_SMALL = 'POPPFIRE'
ADMINLTE4_TITLE = 'POPPFIRE ADMIN'
ADMINLTE4_TITLE_SHORT = 'POPPFIRE'
ADMINLTE_NAVBAR_SKIN = 'primary'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de autenticação
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_URL = '/admin/login/'
