# Generated by Django 5.2.3 on 2026-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink_allowlist', '0002_seed_default_asn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=43, unique=True)),
                ('ip_version', models.PositiveSmallIntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')])),
                ('name', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Prefix',
                'verbose_name_plural': 'Custom Prefixes',
                'ordering': ['ip_version', 'cidr'],
            },
        ),
    ]
