# Generated by Django 5.2.3 on 2026-01-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlink_allowlist', '0003_customprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='starlinkprefix',
            name='region',
            field=models.CharField(
                blank=True,
                help_text='Região (coarse): americas|europe|apac|africa|unknown',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='customprefix',
            name='country',
            field=models.CharField(blank=True, help_text='ISO-3166 alpha-2 (opcional)', max_length=2),
        ),
        migrations.AddField(
            model_name='customprefix',
            name='region',
            field=models.CharField(blank=True, help_text='Região (coarse), ex: americas', max_length=20),
        ),
    ]
