# Generated by Django 5.2.3 on 2025-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('title_visible', models.BooleanField()),
                ('logo', models.CharField(max_length=100)),
                ('logo_visible', models.BooleanField()),
                ('css_header_background_color', models.CharField(max_length=10)),
                ('title_color', models.CharField(max_length=10)),
                ('css_header_text_color', models.CharField(max_length=10)),
                ('css_header_link_color', models.CharField(max_length=10)),
                ('css_header_link_hover_color', models.CharField(max_length=10)),
                ('css_module_background_color', models.CharField(max_length=10)),
                ('css_module_text_color', models.CharField(max_length=10)),
                ('css_module_link_color', models.CharField(max_length=10)),
                ('css_module_link_hover_color', models.CharField(max_length=10)),
                ('css_module_rounded_corners', models.BooleanField()),
                ('css_generic_link_color', models.CharField(max_length=10)),
                ('css_generic_link_hover_color', models.CharField(max_length=10)),
                ('css_save_button_background_color', models.CharField(max_length=10)),
                ('css_save_button_background_hover_color', models.CharField(max_length=10)),
                ('css_save_button_text_color', models.CharField(max_length=10)),
                ('css_delete_button_background_color', models.CharField(max_length=10)),
                ('css_delete_button_background_hover_color', models.CharField(max_length=10)),
                ('css_delete_button_text_color', models.CharField(max_length=10)),
                ('list_filter_dropdown', models.BooleanField()),
                ('related_modal_active', models.BooleanField()),
                ('related_modal_background_color', models.CharField(max_length=10)),
                ('related_modal_rounded_corners', models.BooleanField()),
                ('logo_color', models.CharField(max_length=10)),
                ('recent_actions_visible', models.BooleanField()),
                ('favicon', models.CharField(max_length=100)),
                ('related_modal_background_opacity', models.CharField(max_length=5)),
                ('env_name', models.CharField(max_length=50)),
                ('env_visible_in_header', models.BooleanField()),
                ('env_color', models.CharField(max_length=10)),
                ('env_visible_in_favicon', models.BooleanField()),
                ('related_modal_close_button_visible', models.BooleanField()),
                ('language_chooser_active', models.BooleanField()),
                ('language_chooser_display', models.CharField(max_length=10)),
                ('list_filter_sticky', models.BooleanField()),
                ('form_pagination_sticky', models.BooleanField()),
                ('form_submit_sticky', models.BooleanField()),
                ('css_module_background_selected_color', models.CharField(max_length=10)),
                ('css_module_link_selected_color', models.CharField(max_length=10)),
                ('logo_max_height', models.SmallIntegerField()),
                ('logo_max_width', models.SmallIntegerField()),
                ('foldable_apps', models.BooleanField()),
                ('language_chooser_control', models.CharField(max_length=20)),
                ('list_filter_highlight', models.BooleanField()),
                ('list_filter_removal_links', models.BooleanField()),
                ('show_fieldsets_as_tabs', models.BooleanField()),
                ('show_inlines_as_tabs', models.BooleanField()),
                ('css_generic_link_active_color', models.CharField(max_length=10)),
                ('collapsible_stacked_inlines', models.BooleanField()),
                ('collapsible_stacked_inlines_collapsed', models.BooleanField()),
                ('collapsible_tabular_inlines', models.BooleanField()),
                ('collapsible_tabular_inlines_collapsed', models.BooleanField()),
            ],
            options={
                'db_table': 'admin_interface_theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumoFranquiaUnidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('consumo', models.IntegerField()),
            ],
            options={
                'db_table': 'consumo_franquia_unidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumoFranquiaUnidades2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicelinenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('consumo_priority', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consumo_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'consumo_franquia_unidades2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.TextField()),
                ('shortname', models.TextField()),
                ('type', models.TextField()),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.TextField()),
                ('server', models.TextField(blank=True, null=True)),
                ('community', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nasreload',
            fields=[
                ('nasipaddress', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('reloadtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'nasreload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radacct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.TextField()),
                ('acctuniqueid', models.TextField(unique=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('realm', models.TextField(blank=True, null=True)),
                ('nasipaddress', models.GenericIPAddressField()),
                ('nasportid', models.TextField(blank=True, null=True)),
                ('nasporttype', models.TextField(blank=True, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinterval', models.BigIntegerField(blank=True, null=True)),
                ('acctsessiontime', models.BigIntegerField(blank=True, null=True)),
                ('acctauthentic', models.TextField(blank=True, null=True)),
                ('connectinfo_start', models.TextField(blank=True, null=True)),
                ('connectinfo_stop', models.TextField(blank=True, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.TextField(blank=True, null=True)),
                ('callingstationid', models.TextField(blank=True, null=True)),
                ('acctterminatecause', models.TextField(blank=True, null=True)),
                ('servicetype', models.TextField(blank=True, null=True)),
                ('framedprotocol', models.TextField(blank=True, null=True)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('framedipv6address', models.GenericIPAddressField(blank=True, null=True)),
                ('framedipv6prefix', models.GenericIPAddressField(blank=True, null=True)),
                ('framedinterfaceid', models.TextField(blank=True, null=True)),
                ('delegatedipv6prefix', models.GenericIPAddressField(blank=True, null=True)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('attribute', models.TextField(blank=True, null=True)),
                ('op', models.CharField(blank=True, max_length=2, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radcheck2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('attribute', models.TextField()),
                ('op', models.CharField(max_length=2)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'radcheck2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.TextField()),
                ('attribute', models.TextField()),
                ('op', models.CharField(max_length=2)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'radgroupcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.TextField()),
                ('attribute', models.TextField()),
                ('op', models.CharField(max_length=2)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'radgroupreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radpostauth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('pass_field', models.TextField(blank=True, db_column='pass', null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('calledstationid', models.TextField(blank=True, null=True)),
                ('callingstationid', models.TextField(blank=True, null=True)),
                ('authdate', models.DateTimeField()),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'radpostauth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('attribute', models.TextField()),
                ('op', models.CharField(max_length=2)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radusergroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('groupname', models.TextField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'radusergroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(blank=True, max_length=255, null=True)),
                ('kit', models.CharField(blank=True, max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('negocio_faturamento', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_filial', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade_filial', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=255, null=True)),
                ('data_ativacao', models.CharField(blank=True, max_length=255, null=True)),
                ('servicelinenumber', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'unidades',
                'managed': False,
            },
        ),
    ]
