# Generated by Django 5.2.3 on 2025-06-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radcheck',
            options={'managed': True, 'ordering': ['username', 'attribute'], 'verbose_name': 'Verificação RADIUS', 'verbose_name_plural': 'Verificações RADIUS'},
        ),
    ]
