# Generated by Django 5.2.3 on 2025-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_alter_radcheck_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EldRegistroViewVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('date_view', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Log de Vídeo Assistido',
                'verbose_name_plural': 'Logs de Vídeos Assistidos',
                'db_table': 'eld_registro_view_videos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='radcheck',
            options={'managed': False, 'verbose_name': 'Usuário Radius', 'verbose_name_plural': 'Usuários Radius'},
        ),
    ]
