# Generated by Django 5.2.3 on 2025-07-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_eldregistroviewvideos_alter_radcheck_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radcheck',
            options={'managed': False, 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'managed': False, 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
    ]
