# Generated by Django 5.2.3 on 2025-07-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_alter_radcheck_options_alter_unidades_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarlinkAdminProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Starlink Admin',
                'verbose_name_plural': 'Starlink Admin',
                'managed': False,
            },
        ),
    ]
