# Generated by Django 5.2.3 on 2025-07-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_starlinkadminproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EldUploadVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(help_text='Arquivo de vídeo (máximo 5MB)', max_length=255, upload_to='videos/eld/')),
                ('data', models.DateField(auto_now_add=True, help_text='Data do upload')),
                ('tamanho', models.DecimalField(decimal_places=2, help_text='Tamanho do arquivo em MB', max_digits=10)),
            ],
            options={
                'verbose_name': 'Upload de Vídeo ELD',
                'verbose_name_plural': 'Uploads de Vídeos ELD',
                'db_table': 'eld_upload_videos',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
