# Generated by Django 5.2.3 on 2025-08-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_eldgerenciarportal'),
    ]

    operations = [
        # Recria a tabela eld_gerenciar_portal que foi removida por engano
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS eld_gerenciar_portal (
                id SERIAL PRIMARY KEY,
                ativar_video BOOLEAN NOT NULL DEFAULT FALSE,
                nome_video_id INTEGER,
                captive_portal_zip VARCHAR(100),
                data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                data_atualizacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                ativo BOOLEAN NOT NULL DEFAULT TRUE
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS eld_gerenciar_portal CASCADE;"
        ),
    ]
