# Generated by Django 5.2.3 on 2025-08-03 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_auto_20250801_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='EldPortalSemVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo para este portal', max_length=255, verbose_name='Nome do Portal')),
                ('arquivo_zip', models.FileField(help_text='Arquivo ZIP do portal sem vídeo (scripts_poppnet_sre.zip)', upload_to='portal_sem_video/', verbose_name='Arquivo ZIP')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do portal e suas características', verbose_name='Descrição')),
                ('versao', models.CharField(help_text='Versão do portal (ex: 1.0, 2.1)', max_length=50, verbose_name='Versão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativo', models.BooleanField(default=False, help_text='Marcar como portal padrão para uso sem vídeo', verbose_name='Portal Ativo')),
                ('tamanho_mb', models.DecimalField(decimal_places=2, help_text='Tamanho do arquivo ZIP em MB', max_digits=10, verbose_name='Tamanho (MB)')),
            ],
            options={
                'verbose_name': 'Portal sem Vídeo',
                'verbose_name_plural': 'Portais sem Vídeo',
                'db_table': 'eld_portal_sem_video',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.AlterField(
            model_name='eldgerenciarportal',
            name='captive_portal_zip',
            field=models.FileField(blank=True, help_text='Upload do arquivo .zip contendo os arquivos do portal captive (src.zip)', null=True, upload_to='captive_portal_zips/', verbose_name='Arquivo ZIP do Portal (com vídeo)'),
        ),
        migrations.AddField(
            model_name='eldgerenciarportal',
            name='portal_sem_video',
            field=models.ForeignKey(blank=True, help_text='Portal usado quando vídeo estiver desativado (scripts_poppnet_sre.zip)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_portal', to='painel.eldportalsemvideo', verbose_name='Portal sem Vídeo'),
        ),
    ]
