# Generated by Django 5.2.3 on 2025-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_eldportalsemvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldportalsemvideo',
            name='preview',
            field=models.ImageField(blank=True, help_text='Imagem de preview/screenshot do portal', null=True, upload_to='portais_sem_video/previews/', verbose_name='Preview do Portal'),
        ),
    ]
