# Generated by Django 5.2.3 on 2026-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_add_preview_to_portal_sem_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eldportalsemvideo',
            name='preview',
        ),
        migrations.AlterField(
            model_name='eldgerenciarportal',
            name='ativar_video',
            field=models.BooleanField(default=False, help_text='Ativar para permitir que o Appliance POPPFIRE baixe e exiba vídeos no portal captive', verbose_name='Ativar Vídeo'),
        ),
    ]
