# Generated by Django 5.2.3 on 2025-07-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel', '0006_elduploadvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptivePortalProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Gerenciar Captive Portal',
                'verbose_name_plural': 'Gerenciar Captive Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.elduploadvideo',),
        ),
        migrations.CreateModel(
            name='LogsVideosProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Logs de Vídeos Assistidos',
                'verbose_name_plural': 'Logs de Vídeos Assistidos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldregistroviewvideos',),
        ),
        migrations.CreateModel(
            name='UploadVideosProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Listagem de Vídeos',
                'verbose_name_plural': 'Listagem de Vídeos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.elduploadvideo',),
        ),
        migrations.CreateModel(
            name='EldGerenciarPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativar_video', models.BooleanField(default=False, help_text='Ativar para permitir que o OpenSense baixe e exiba vídeos no portal captive', verbose_name='Ativar Vídeo')),
                ('captive_portal_zip', models.FileField(blank=True, help_text='Upload do arquivo .zip contendo os arquivos do portal captive', null=True, upload_to='captive_portal_zips/', verbose_name='Arquivo ZIP do Portal')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas uma configuração pode estar ativa por vez', verbose_name='Configuração Ativa')),
                ('nome_video', models.ForeignKey(blank=True, help_text='Selecione o vídeo que será exibido no portal captive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_configurations', to='painel.elduploadvideo', verbose_name='Vídeo Selecionado')),
            ],
            options={
                'verbose_name': 'Configuração do Portal Captive',
                'verbose_name_plural': 'Configurações do Portal Captive',
                'db_table': 'eld_gerenciar_portal',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='GerenciarPortalProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Configuração do Portal',
                'verbose_name_plural': 'Configuração do Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('captive_portal.eldgerenciarportal',),
        ),
    ]
