# Generated by Django 5.2.3 on 2025-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel', '0007_eldgerenciarportal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptivePortalProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Gerenciar Captive Portal',
                'verbose_name_plural': 'Gerenciar Captive Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.elduploadvideo',),
        ),
        migrations.CreateModel(
            name='LogsVideosProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Logs de Vídeos Assistidos',
                'verbose_name_plural': 'Logs de Vídeos Assistidos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldregistroviewvideos',),
        ),
        migrations.CreateModel(
            name='UploadVideosProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Listagem de Vídeos',
                'verbose_name_plural': 'Listagem de Vídeos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.elduploadvideo',),
        ),
    # EldGerenciarPortal é definido no app 'painel' (painel/migrations/0007_eldgerenciarportal)
        migrations.CreateModel(
            name='GerenciarPortalProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Configuração do Portal',
                'verbose_name_plural': 'Configuração do Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldgerenciarportal',),
        ),
    ]
