"""
Fix proxy base before removing EldGerenciarPortal to avoid InvalidBasesError.

This migration replaces the GerenciarPortalProxy to base on painel.EldGerenciarPortal
and then safely removes the temporary EldGerenciarPortal model that existed in
the captive_portal app from 0001.
"""

# Generated by Django 5.2.3 on 2025-08-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0001_initial'),
        ('painel', '0007_eldgerenciarportal'),
    ]

    operations = [
        # Drop the old proxy that depends on captive_portal.EldGerenciarPortal
        migrations.DeleteModel(
            name='GerenciarPortalProxy',
        ),

        # Recreate the proxy pointing to painel.EldGerenciarPortal to keep admin menus
        migrations.CreateModel(
            name='GerenciarPortalProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Configuração do Portal',
                'verbose_name_plural': 'Configuração do Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldgerenciarportal',),
        ),

        # Now it is safe to remove the temporary model from captive_portal
        migrations.DeleteModel(
            name='EldGerenciarPortal',
        ),
    ]
