# Generated by Django 5.2.3 on 2025-08-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EldGerenciarPortal',
        ),
    ]
