"""captive_portal migration 0002.

Originally intended to fix proxy bases and remove a temporary
``captive_portal.EldGerenciarPortal`` model.

In this repo, ``0001_initial`` already defines ``GerenciarPortalProxy`` based on
``painel.EldGerenciarPortal`` and does *not* create a concrete
``captive_portal.EldGerenciarPortal`` model. Attempting to delete it causes a
KeyError during migrations.

So this migration only ensures the proxy base is correct.
"""

# Generated by Django 5.2.3 on 2025-08-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0001_initial'),
        ('painel', '0007_eldgerenciarportal'),
    ]

    operations = [
        # Drop the old proxy that depends on captive_portal.EldGerenciarPortal
        migrations.DeleteModel(
            name='GerenciarPortalProxy',
        ),

        # Recreate the proxy pointing to painel.EldGerenciarPortal to keep admin menus
        migrations.CreateModel(
            name='GerenciarPortalProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Configuração do Portal',
                'verbose_name_plural': 'Configuração do Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldgerenciarportal',),
        ),
    ]
