# Generated by Django 5.2.3 on 2025-08-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0002_delete_eldgerenciarportal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captiveportalproxy',
            options={'verbose_name': 'Gerenciar Vídeos', 'verbose_name_plural': 'Gerenciar Vídeos'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarportalproxy',
            options={'verbose_name': 'Gerenciar Captive Portal', 'verbose_name_plural': 'Gerenciar Captive Portal'},
        ),
    ]
