# Generated by Django 5.2.3 on 2025-08-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0003_alter_captiveportalproxy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token único para autenticação', max_length=64, unique=True)),
                ('appliance_id', models.CharField(help_text='ID único do appliance', max_length=100, unique=True)),
                ('appliance_name', models.CharField(help_text='Nome descritivo do appliance', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição adicional do appliance', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se o token está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Última vez que o token foi usado', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Último IP que usou o token', null=True)),
            ],
            options={
                'verbose_name': 'Token do Appliance POPPFIRE',
                'verbose_name_plural': 'Tokens dos Appliances POPPFIRE',
                'ordering': ['-created_at'],
            },
        ),
    ]
