# Generated by Django 5.2.3 on 2026-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0004_appliancetoken'),
        ('painel', '0011_remove_eldportalsemvideo_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Sistema de Notificações',
                'verbose_name_plural': 'Sistema de Notificações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldgerenciarportal',),
        ),
        migrations.CreateModel(
            name='PortalSemVideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Portal sem Vídeo',
                'verbose_name_plural': 'Gerenciar Portal sem Vídeo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldportalsemvideo',),
        ),
        migrations.CreateModel(
            name='ZipManagerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Gerenciar ZIP Portal',
                'verbose_name_plural': 'Gerenciar ZIP Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('painel.eldgerenciarportal',),
        ),
        migrations.AlterModelOptions(
            name='captiveportalproxy',
            options={'verbose_name': 'Captive Portal', 'verbose_name_plural': 'Captive Portal'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarportalproxy',
            options={'verbose_name': 'Gerenciar Portal com Vídeo', 'verbose_name_plural': 'Gerenciar Portal com Vídeo'},
        ),
        migrations.AlterModelOptions(
            name='logsvideosproxy',
            options={'verbose_name': 'Logs de Vídeos', 'verbose_name_plural': 'Logs de Vídeos'},
        ),
        migrations.AlterModelOptions(
            name='uploadvideosproxy',
            options={'verbose_name': 'Gerenciar Vídeos', 'verbose_name_plural': 'Gerenciar Vídeos'},
        ),
        migrations.AlterField(
            model_name='appliancetoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
